version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  user-service:
    build: ./user-service
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+pymysql://root:root@db:3306/userdb"

  transaction-service:
    build:
      context: ./transaction_service
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "50051:50051"
    environment:
      DATABASE_URL: "mysql+pymysql://root:root@db:3306/transactiondb"

  analytics-service:
    build: ./analytics-service
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - "8002:8002"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      AMQP_URI: "amqp://guest:guest@rabbitmq/"
      TEST_MODE: "true"

  api-gateway-web:
    build: ./api-gateway-web
    ports:
      - "3000:3000"
    environment:
      USER_SERVICE_URL: "http://user-service:8000"
      TRANSACTION_SERVICE_URL: "http://transaction-service:50051"
      ANALYTICS_SERVICE_URL: "http://analytics-service:8002"

  api-gateway-mobile:
    build: ./api-gateway-mobile
    ports:
      - "5000:5000"
    environment:
      USER_SERVICE_URL: "http://user-service:8000"
      TRANSACTION_SERVICE_URL: "transaction-service:50051"
      ANALYTICS_SERVICE_URL: "http://analytics-service:8002"

  user-mf:
    build: ./user-mf
    ports:
      - "8081:8080"

  transaction-mf:
    build: ./transaction-mf
    ports:
      - "8082:8080"

  analytics-mf:
    build: ./analytics-mf
    ports:
      - "8083:8080"

  web-app-container:
    build: ./web-app-container
    ports:
      - "8080:8080"

volumes:
  dbdata:
  mongodata:
