name: Analytics Service CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmq-diagnostics check_running"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      AMQP_URI: amqp://guest:guest@rabbitmq/
      MONGO_URI: mongodb://mongo:27017
      PYTHONPATH: analytics-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r analytics-service/requirements.txt

      - name: Wait for MongoDB and RabbitMQ
        run: sleep 15

      - name: Start analytics-service in background
        run: |
          export MONGO_URI=$MONGO_URI
          export AMQP_URI=$AMQP_URI
          PYTHONPATH=analytics-service nohup python analytics-service/app/main.py > analytics-service.log 2>&1 &
          sleep 5

      - name: Run Analytics Endpoint Tests
        run: pytest analytics-service/tests/test_analytics.py

      - name: Run RabbitMQ Integration Test
        run: pytest analytics-service/tests/test_consumer.py

      - name: Show analytics-service logs
        if: always()
        run: cat analytics-service.log
